# -*- coding: utf-8 -*-
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.support.ui import Select
from selenium.common.exceptions import NoSuchElementException
from selenium.common.exceptions import NoAlertPresentException
import unittest, time, re
import time

driver = webdriver.Firefox()
driver.get("http://dvwa.f5demo.com/login.php")
driver.find_element_by_name("username").click()
driver.find_element_by_name("username").clear()
driver.find_element_by_name("username").send_keys("admin")
driver.find_element_by_name("password").clear()
driver.find_element_by_name("password").send_keys("password")
driver.find_element_by_name("password").send_keys(Keys.ENTER)
driver.get("http://dvwa.f5demo.com/instructions.php")
driver.get("http://dvwa.f5demo.com/setup.php")
driver.find_element_by_name("create_db").click()
driver.get("http://dvwa.f5demo.com/vulnerabilities/logout.php")
driver.get("http://dvwa.f5demo.com/login.php")
driver.find_element_by_name("username").click()
driver.find_element_by_name("username").clear()
driver.find_element_by_name("username").send_keys("admin")
driver.find_element_by_name("password").clear()
driver.find_element_by_name("password").send_keys("password")
driver.find_element_by_name("password").send_keys(Keys.ENTER)
driver.get("http://dvwa.f5demo.com/vulnerabilities/brute")
driver.find_element_by_name("username").click()
driver.find_element_by_name("username").clear()
driver.find_element_by_name("username").send_keys("user1")
driver.find_element_by_name("password").clear()
driver.find_element_by_name("password").send_keys("user1")
driver.find_element_by_xpath("//form[@action='#']").click()
driver.find_element_by_name("Login").click()
time.sleep(2)
driver.find_element_by_name("username").click()
driver.find_element_by_name("username").clear()
driver.find_element_by_name("username").send_keys("user2")
driver.find_element_by_xpath("//div[@id='main_body']/div").click()
driver.find_element_by_name("password").click()
driver.find_element_by_name("password").clear()
driver.find_element_by_name("password").send_keys("user2")
driver.find_element_by_xpath("//form[@action='#']").click()
driver.find_element_by_xpath("//div[@id='main_body']/div/div").click()
driver.find_element_by_name("Login").click()
time.sleep(2)
driver.get("http://dvwa.f5demo.com/vulnerabilities/exec")
driver.find_element_by_name("ip").click()
driver.find_element_by_name("ip").clear()
driver.find_element_by_name("ip").send_keys("10.1.20.50")
driver.find_element_by_name("submit").click()
time.sleep(3)
driver.get("http://dvwa.f5demo.com/vulnerabilities/xss_s")
driver.find_element_by_name("txtName").click()
driver.find_element_by_name("txtName").clear()
driver.find_element_by_name("txtName").send_keys("Hello World")
driver.find_element_by_name("mtxMessage").click()
driver.find_element_by_name("mtxMessage").clear()
driver.find_element_by_name("mtxMessage").send_keys("This is a great space for comments. \n<script>alert(document.cookie)</script>")
driver.find_element_by_name("btnSign").click()
time.sleep(3)
driver.get("http://dvwa.f5demo.com/phpinfo.php")
time.sleep(1)
driver.get("http://dvwa.f5demo.com/logout.php")
time.sleep(1)
driver.quit()
    